[package]
name = "generator-rs"
version = "0.1.0"
authors = ["MH11097 <mh11097@example.com>"]
edition = "2021"

[dependencies]
comrak = "0.24"
regex = "1.10"
rss = "2.0"
time = "0.3"
dotenv = "0.15"
rouille = "3.6"
chrono = { version = "0.4", features = ["serde"] }