# Site settings
title: "MH11097's Tech Blog"
email: your.email@domain.com
description: >-
  Welcome to my tech blog where I share insights about programming, technology, and development experiences.
baseurl: ""
url: "https://MH11097.github.io"
twitter_username: MH11097
github_username: MH11097

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
  auto_ids: true

# Plugins (GitHub Pages supported only)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination (GitHub Pages style)
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:name/
  tags:
    output: true
    permalink: /tags/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "with-sidebar"
      math: true
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "posts"
    values:
      layout: "posts"
  - scope:
      path: "tags"
    values:
      layout: "with-sidebar"

# Scientific settings
math: true
code_highlighting: true

# Navigation
navigation:
  - title: "Trang chủ"
    url: "/"
    icon: "icon-home"
  - title: "Bài viết"
    url: "/posts/"
    icon: "icon-doc-text"
  - title: "Thẻ"
    url: "/tags/"
    icon: "icon-tag"
  - title: "CV"
    url: "/cv.html"
    icon: "icon-doc"

# Exclude from processing
exclude:
  - .claude/
  - .serena/
  - docs/
  - scripts/
  - gen
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - posts/
  - css/
  - js/
  - font/
  - img/
  - emoji/
  - content/
  - generator-rs/
  - templates/
  - js-QUYNHNN/

# Include
include:
  - _pages
